name: Pixel Game Engine - Syntax Check

on:
  push:
    branches: [ master, test ]
  pull_request:
    branches: [ master, test ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check TEST_Animate2D.cpp
      run: g++ -fsyntax-only examples/TEST_Animate2D.cpp -I.
    - name: Check TEST_Camera2D.cpp
      run: g++ -fsyntax-only examples/TEST_Camera2D.cpp -I.
    - name: Check TEST_QuickGUI.cpp
      run: g++ -fsyntax-only examples/TEST_QuickGUI.cpp -I.